### ISSUE TITLE
Vegas keeps Reloading Images which causes Browser not to render properly (sometimes)

### ISSUE THREAD

**Issue by jackmorizo** [jaysalvat/vegas#67]
Hey guys,

I work for a big Web-Agency in Austria and we use vegas for Background-Images.
Unfortunately we get Black and White Gaps at the Bottom of the Images.
(Problem occurs on FF 35.0 and some Firmware-Browsers of Samsung-Android-Phones)

I've checked the Problem and it seems, that the Browser needs to Render the images again and again because they get loaded always (even if they were loaded already before)

![image](https://cloud.githubusercontent.com/assets/5560083/5901258/46bf2a6e-a571-11e4-8240-a41715e1cb4d.png)

It seems the problem is the way how the images are displayed.
basically you always override the "src"-Attribute which there fore forces the browser to reload the image. (I still don't know why the Browser behaves like this .. the image should be cached)

![image](https://cloud.githubusercontent.com/assets/5560083/5901340/0993a0ec-a572-11e4-90ae-28e826bdc4fe.png)

I Like your solution for the Sliding because it does not kill your RAM but it seems that it causes some Rendering-Issues because the images are not fully loaded when the slider switches.

Here you have an Example-Screenshot of the resulting Problem
![image](https://cloud.githubusercontent.com/assets/5560083/5901417/aed5a686-a572-11e4-9223-def3ff69a00f.png)

**Comment by jaysalvat** [comment]
Hello!

The white gap is a known issue on Android. I have no android device to fix it.

For the never-ending image reloading, I've just check on Chrome / Firefox on MAC and no problem.
Are you sure cache is not disabled with devtools open ?

The overide src is a trick to trigger onload with images on IE. Otherwise no onload event with cached pictures.

**Comment by Gweg83** [comment]
Hello et sorry for my bad english

I have exactly the same issues
After many test the problem is on firefox 35 with hardware acceleration 
Disable hardware acceleration fixes the problem

![capture](https://cloud.githubusercontent.com/assets/10776435/5980120/a9a69e84-a8ad-11e4-9603-d7dae601ebb9.JPG)

Thank you and good day

**Comment by jackmorizo** [comment]
You are right about the endless Image-Reloading .. I've checked Safari, Chrome and FF on Mac and Chrome and FF on Windows .. the Image reloading happens only because of Firebug (Native Debugging-Tools are fine)

But the Black-Gap at the bottom still occures on FF 35 .. on FF34 and all other browsers it's fine .. I guess it's a bug of the browser you could only handle with an ugly workaround

**Comment by jaysalvat** [comment]
Ok :)

For the black gap, if it works everywhere but on FF35. It's a "browser bug". It can't fix all that kind of browser surprise.

I hope Vegas 2 (work in progress) will work better.

Regards.

**Comment by jackmorizo** [comment]
Thanks :)
