### ISSUE TITLE
Attach vegas slider to a div (not BODY)

### ISSUE THREAD

**Issue by redworx** [jaysalvat/vegas#69]
It would be a nice feature, if it would be possible to attache the slider to a DIV.

e.g: $('mydiv').vegas();

I don't want the slider on the full size BODY tag. I want the slider loaded into a div with width and height.

**Comment by jaysalvat** [comment]
Hello.
V2 will have this feature.
Released in a few weeks.

**Comment by redworx** [comment]
perfect!

**Comment by hugomsgomes** [comment]
I'm trying version  2.1.3 and tried to do it an only work for tag 'body' if i change it to '#mydiv' not work!!

**Comment by jaysalvat** [comment]
Hello Hugo,

Do the Vegas website and the demo work on your browser?

http://vegas.jaysalvat.com/documentation/setup/
http://vegas.jaysalvat.com/demo/

**Comment by hugomsgomes** [comment]
Hi Jay,


     In the website everything is ok, i could see the slideshow in the body
and in the demo box. I've found my basic mistake, after put the start ot
the demo inside a on ready jquery funtion it started working. I supposed
this was not necessary since for body tag it worked without this!!

     Thanks very much for you answer.

     Best regards,
     Hugo Gomes


On Sat, May 30, 2015 at 6:27 PM, Jay Salvat <notifications@github.com>
wrote:

> Hello Hugo,
>
> Do the Vegas website and the demo work on your browser?
>
> http://vegas.jaysalvat.com/documentation/setup/
> http://vegas.jaysalvat.com/demo/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaysalvat/vegas/issues/69#issuecomment-107067839>.
>



-- 
------------------------
Hugo Gomes
URL: www.hmsg.net
Email: hmsg.net@gmail.com
------------------------

**Comment by jaysalvat** [comment]
Great Hugo!

Yes, if you set Vegas before the DOM element is created, it can work.
You can use the jQuery ready solution or set Vegas at the end of the page.

Regards.

__

Jay Salvat
http://www.jaysalvat.com
